# GitHub Actions
# https://github.com/features/actions

# GitHub CLI
# https://cli.github.com

name: Release CI

on: [push, pull_request]

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        run: |
          git tag --force nightly
          git push --force origin nightly

          gh release delete nightly --yes || true
          gh release create nightly --title 'Nightly builds' --notes-file CHANGELOG.md --prerelease
        env:
          GIT_CONFIG_NOSYSTEM: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build release
    needs: release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            install-packages:
          - os: macos-latest
            target: x86_64-apple-darwin
            install-packages: brew install crystal
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: ${{ matrix.install-packages }}

      - name: Build release
        run: make release name=webextension-shell version=nightly target=${{ matrix.target }}
        working-directory: host

      - name: Upload release
        run: gh release upload nightly releases/webextension-shell-nightly-${{ matrix.target }}.zip
        working-directory: host
        env:
          GIT_CONFIG_NOSYSTEM: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
